server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource-fc:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/financescontrolldb
    username: postgres
    password: root
  datasource-oauth:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
host:
  full:
    dns:
      auth:
        link: http://localhost:8081/oauth/token
